### ISSUE TITLE
Cascading and scoping

### ISSUE THREAD

**Issue by ArmorDarks** [luwes/postcss-var-shim#1]
Hi!

Thanks a lot for your efforts in making maintaining older browsers easier!

I've tested your plugin, and it works! However, it turned out, that it can't handle scoping and cascading.

In other words, this:

```css
:root {
  --test-color: red;
  --test-bg: blue;
}

.Test {
  color: var(--test-color);
  background-color: var(--test-bg);
}

.Test.is-other {
  --test-color: yellow;
  --test-bg: white;
}

.is-scoped {
  --test-color: green;
  --test-bg: yellow;
}
```

will produce different results in Chrome and IE:

Chrome:

![chrome_2017-11-05_21-02-28](https://user-images.githubusercontent.com/4460311/32418124-b76f2a3c-c26c-11e7-9e88-4ee0832d32c6.png)

IE:

![iexplore_2017-11-05_21-02-41](https://user-images.githubusercontent.com/4460311/32418125-bd79671c-c26c-11e7-86ee-ef1f318fb90b.png)

Well, the scoping and cascading is the only feature of CSS variables that makes them better choice for some tasks, otherwise they aren't much different from preprocessors variables.

I wonder, are there any plans to introduces shim for scoping and cascading too? That would be glorious...
